# Generated by Django 5.0.6 on 2024-05-15 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='genres',
            new_name='genre',
        ),
        migrations.AddField(
            model_name='movie',
            name='poster',
            field=models.URLField(default='https://via.placeholder.com/150'),
        ),
    ]
