# Generated by Django 5.0.6 on 2024-05-15 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_alter_genre_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='year',
            field=models.IntegerField(help_text='Release year'),
        ),
    ]
